project:
  type: website
  output-dir: ../../docs
  render:
    - "*.qmd"

website:
  title: "Physics Journal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: linear-algebra.qmd
        text: Linear Algebra
      - href: linear-transformations.qmd
        text: Linear Transformations
      - href: matrix-transform-playground.qmd
        text: Matrix Playground
  sidebar:
    style: docked
    contents:
      - index.qmd
      - linear-algebra.qmd
      - linear-transformations.qmd
      - matrix-transform-playground.qmd

format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    code-fold: true
    fig-responsive: true

execute:
  freeze: auto
